openapi: 3.0.0
info:
  title: nextjs-for-swr-todo
  version: '1.0'
servers:
  - url: 'http://localhost:3001/api/v1'
    description: local
paths: {}
components:
  schemas:
    Todo:
      title: Todo
      type: object
      properties:
        todo:
          type: object
          properties:
            name:
              type: string
            is_completed:
              type: boolean
tags:
  - name: Todo
  - name: User
