openapi: 3.0.0
info:
  title: nextjs-for-swr-todo
  version: '1.0'
servers:
  - url: 'http://localhost:3001/api/v1'
    description: local
paths:
  /todos:
    get:
      summary: Get All Todos
      tags:
        - Todo
      responses:
        '200':
          $ref: '#/components/responses/Todos'
      operationId: get-todos
    post:
      summary: Create a Todo
      tags:
        - Todo
      responses:
        '200':
          $ref: '#/components/responses/Todo'
      operationId: create-todos
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
  '/todos/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    put:
      summary: Update a Todo
      tags:
        - Todo
      operationId: update-todo-by-id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
      responses:
        '200':
          $ref: '#/components/responses/Todo'
    delete:
      summary: Delete a Todo
      tags:
        - Todo
      responses:
        '204':
          description: No Content
      operationId: delete-todos-id
    get:
      summary: ''
      operationId: get-todo-by-id
      responses:
        '200':
          $ref: '#/components/responses/Todo'
      tags:
        - Todo
components:
  schemas:
    Todo:
      title: Todo
      type: object
      properties:
        todo:
          type: object
          properties:
            name:
              type: string
            is_completed:
              type: boolean
            id:
              type: string
  responses:
    Todos:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              todos:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    is_completed:
                      type: boolean
    Todo:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Todo'
tags:
  - name: Todo
  - name: User
